[debug] [2024-12-09T21:42:22.946Z] ----------------------------------------------------------------------
[debug] [2024-12-09T21:42:22.951Z] Command:       /nix/store/if6aqyl3sl0hz14a12mndj35swb1mcwi-nodejs-20.17.0/bin/node /nix/store/wg0myk7djggj0f2327nkpm9r2w8q6lp8-firebase-tools-13.27.0/lib/node_modules/firebase-tools/lib/bin/firebase.js
[debug] [2024-12-09T21:42:22.952Z] CLI Version:   13.27.0
[debug] [2024-12-09T21:42:22.952Z] Platform:      linux
[debug] [2024-12-09T21:42:22.952Z] Node Version:  v20.17.0
[debug] [2024-12-09T21:42:22.952Z] Time:          Mon Dec 09 2024 21:42:22 GMT+0000 (Coordinated Universal Time)
[debug] [2024-12-09T21:42:22.952Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-12-09T21:42:22.957Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-12-09T21:42:23.068Z] TypeError: Cannot read properties of undefined (reading '0')
    at Command.<anonymous> (/nix/store/wg0myk7djggj0f2327nkpm9r2w8q6lp8-firebase-tools-13.27.0/lib/node_modules/firebase-tools/lib/index.js:58:21)
    at Command.listener [as _actionHandler] (/nix/store/wg0myk7djggj0f2327nkpm9r2w8q6lp8-firebase-tools-13.27.0/lib/node_modules/firebase-tools/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/nix/store/wg0myk7djggj0f2327nkpm9r2w8q6lp8-firebase-tools-13.27.0/lib/node_modules/firebase-tools/node_modules/commander/index.js:914:14)
    at Command.parse (/nix/store/wg0myk7djggj0f2327nkpm9r2w8q6lp8-firebase-tools-13.27.0/lib/node_modules/firebase-tools/node_modules/commander/index.js:717:10)
    at Object.<anonymous> (/nix/store/wg0myk7djggj0f2327nkpm9r2w8q6lp8-firebase-tools-13.27.0/lib/node_modules/firebase-tools/lib/bin/firebase.js:129:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-12-09T21:42:23.178Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2024-12-09T21:42:23.179Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
